---
sidebar: sidebar 
permalink: rename_storage.html 
keywords:  
summary: 'È possibile rinominare l"archiviazione utilizzando l"API REST.' 
---
= Ripristina il backup dell'archivio rinominato
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando l'archiviazione veniva rinominata, i flussi di lavoro che utilizzavano backup eseguiti prima della ridenominazione non riuscivano.  Con l'introduzione della funzionalità di backup di ridenominazione, accessibile esclusivamente tramite API REST, è ora possibile utilizzare i backup eseguiti prima della ridenominazione dello storage.  Di seguito vengono descritti il flusso di lavoro e l'utilizzo dell'API REST.


NOTE: Il sistema di archiviazione ASA r2 non supporta la funzionalità di denominazione degli snapshot _recent.

.Passi
. Aggiungere o aggiornare la nuova connessione di archiviazione, assicurandosi che il nuovo nome del cluster o della SVM venga riflesso in SCV.
. Riavviare il servizio per aggiornare le cache come descritto nell'articolo della Knowledge Base: https://kb.netapp.com/mgmt/SnapCenter/SCV_backups_fail_after_SVM_rename["I backup SCV falliscono dopo la ridenominazione di SVM"]
. Crea un nuovo backup.
. Utilizzare i dettagli del backup per trovare i nomi degli archivi vecchi e nuovi.
. Nella schermata *Backup* del client vSphere, seleziona il backup per visualizzarne i dettagli.
. Accedi a Swagger dall'URL: `\https://<SCV-IP>:8144/api/swagger-ui/index.html`
+
Utilizzare la seguente API per rinominare l'archivio:

+
PATCH /4.1/sistema-di-archiviazione

+
Esempio: { "existingSVM": { "name": "string" }, "newSVM": { "name": "string" } }

+
Risposta:

+
{ "statusMessage": "OK", "statusCode": 200, "responseMessage": [ "Sistema di archiviazione rinominato correttamente."  ] }

+
Dopo aver eseguito questa API, sarai in grado di eseguire tutti i flussi di lavoro, inclusa l'operazione di ripristino dal vecchio backup.


