---
sidebar: sidebar 
permalink: scpivs44_search_for_backups.html 
keywords:  
summary: È possibile cercare e trovare un backup specifico di una VM o di un datastore utilizzando la procedura guidata di ripristino.  Dopo aver individuato un backup, è possibile ripristinarlo. 
---
= Cerca backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile cercare e trovare un backup specifico di una VM o di un datastore utilizzando la procedura guidata di ripristino.  Dopo aver individuato un backup, è possibile ripristinarlo.

.Passi
. Nell'interfaccia utente grafica del client VMware vSphere, seleziona *Menu* nella barra degli strumenti, quindi esegui una delle seguenti operazioni:
+
|===
| Per visualizzare i backup per… | Fai quanto segue… 


| VM | Selezionare l'opzione di menu *Host e cluster*, quindi selezionare una VM, quindi selezionare la scheda *Configura* e infine selezionare *Backup* nella sezione * SnapCenter Plug-in for VMware vSphere *. 


| Datastore | Selezionare l'opzione di menu *Archiviazione*, quindi selezionare un datastore, quindi selezionare la scheda *Configura* e infine selezionare *Backup* nella sezione * SnapCenter Plug-in for VMware vSphere*. 
|===
. Nel riquadro di navigazione a sinistra, espandere il data center che contiene la VM o il datastore.
. Facoltativo: fare clic con il pulsante destro del mouse su una VM o un datastore, quindi selezionare * SnapCenter Plug-in for VMware vSphere* nell'elenco a discesa, quindi selezionare *Ripristina* nell'elenco a discesa secondario.
. Nella procedura guidata *Ripristina* immettere un nome di ricerca e selezionare *Cerca*.
+
È possibile filtrare l'elenco dei backup selezionando l'icona del filtro e selezionando un intervallo di data e ora, specificando se si desiderano backup contenenti snapshot VMware, se si desiderano backup montati e la posizione. Selezionare *OK*.


