---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: 'È possibile ripristinare file o cartelle da un disco di macchina virtuale (VMDK) su un sistema operativo guest Windows.' 
---
= Flusso di lavoro, prerequisiti e limitazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile ripristinare file o cartelle da un disco di macchina virtuale (VMDK) su un sistema operativo guest Windows.



== Flusso di lavoro di ripristino degli ospiti

Le operazioni di ripristino del sistema operativo guest includono i seguenti passaggi:

. Allegare
+
Collegare un disco virtuale a una macchina virtuale guest o a una macchina virtuale proxy e avviare una sessione di ripristino dei file guest.

. Aspettare
+
Attendi il completamento dell'operazione di collegamento prima di poter esplorare e ripristinare.  Quando l'attacco

+
Al termine dell'operazione, viene creata automaticamente una sessione di ripristino del file guest e viene inviata una notifica via e-mail

+
inviato.

. Seleziona file o cartelle
+
Sfoglia il VMDK nella sessione Guest File Restore e seleziona uno o più file o cartelle da ripristinare.

. Ripristinare
+
Ripristina i file o le cartelle selezionati in una posizione specificata.





== Prerequisiti per il ripristino di file e cartelle guest

Prima di ripristinare uno o più file o cartelle da un VMDK su un sistema operativo guest Windows, è necessario conoscere tutti i requisiti.

* Gli strumenti VMware devono essere installati e in esecuzione.
+
SnapCenter utilizza le informazioni degli strumenti VMware per stabilire una connessione al sistema operativo guest VMware.

* Il sistema operativo guest Windows deve eseguire Windows Server 2008 R2 o versione successiva.
+
Per le informazioni più recenti sulle versioni supportate, fare riferimento a https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp (IMT)"^] .

* Le credenziali per la macchina virtuale di destinazione devono specificare l'account amministratore di dominio predefinito o l'account amministratore locale predefinito.  Il nome utente deve essere "Amministratore".  Prima di avviare l'operazione di ripristino, è necessario configurare le credenziali per la VM a cui si desidera collegare il disco virtuale.  Le credenziali sono necessarie sia per l'operazione di collegamento che per la successiva operazione di ripristino.  Gli utenti del gruppo di lavoro possono utilizzare l'account amministratore locale integrato.
+

IMPORTANT: Se è necessario utilizzare un account che non è l'account amministratore predefinito, ma dispone di privilegi amministrativi all'interno della VM, è necessario disabilitare UAC sulla VM guest.

* È necessario conoscere lo snapshot di backup e il VMDK da cui eseguire il ripristino.
+
Il SnapCenter Plug-in for VMware vSphere non supporta la ricerca di file o cartelle da ripristinare.  Pertanto, prima di iniziare è necessario conoscere la posizione dei file o delle cartelle rispetto allo snapshot e al VMDK corrispondente.

* Il disco virtuale da collegare deve trovarsi in un backup SnapCenter .
+
Il disco virtuale che contiene il file o la cartella che si desidera ripristinare deve trovarsi in un backup della VM eseguito utilizzando l'appliance virtuale per il SnapCenter Plug-in for VMware vSphere.

* Per utilizzare una VM proxy, è necessario configurarla.
+
Se si desidera collegare un disco virtuale a una VM proxy, la VM proxy deve essere configurata prima che inizi l'operazione di collegamento e ripristino.

* Per i file con nomi in un alfabeto diverso dall'inglese, è necessario ripristinarli in una directory e non come un singolo file.
+
È possibile ripristinare i file con nomi non alfabetici, come i Kanji giapponesi, ripristinando la directory in cui si trovano i file.

* Il ripristino da un sistema operativo guest Linux non è supportato
+
Non è possibile ripristinare file e cartelle da una macchina virtuale che esegue il sistema operativo guest Linux.  Tuttavia, è possibile allegare un VMDK e quindi ripristinare manualmente i file e le cartelle.  Per le informazioni più recenti sui sistemi operativi guest supportati, fare riferimento a https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp (IMT)"^] .





== Limitazioni del ripristino dei file guest

Prima di ripristinare un file o una cartella da un sistema operativo guest, è opportuno sapere cosa non è supportato dalla funzionalità.

* Non è possibile ripristinare tipi di dischi dinamici all'interno di un sistema operativo guest.
* Se si ripristina un file o una cartella crittografati, l'attributo di crittografia non viene mantenuto.  Non è possibile ripristinare file o cartelle in una cartella crittografata.
* La pagina Esplora file ospite visualizza i file e le cartelle nascosti, che non è possibile filtrare.
* Non è possibile effettuare il ripristino da un sistema operativo guest Linux.
+
Non è possibile ripristinare file e cartelle da una macchina virtuale che esegue il sistema operativo guest Linux.  Tuttavia, è possibile allegare un VMDK e quindi ripristinare manualmente i file e le cartelle.  Per le informazioni più recenti sui sistemi operativi guest supportati, fare riferimento a https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp (IMT)"^] .

* Non è possibile ripristinare da un file system NTFS a un file system FAT.
+
Quando si tenta di ripristinare dal formato NTFS al formato FAT, il descrittore di sicurezza NTFS non viene copiato perché il file system FAT non supporta gli attributi di sicurezza di Windows.

* Non è possibile ripristinare i file guest da un VMDK clonato o da un VMDK non inizializzato.
* Non è possibile ripristinare la struttura della directory di un file.
+
Se si seleziona un file in una directory nidificata per il ripristino, il file non viene ripristinato con la stessa struttura di directory.  Non viene ripristinato l'albero delle directory, ma solo il file.  Se si desidera ripristinare una struttura di directory, è possibile copiare la directory stessa nella parte superiore della struttura.

* Non è possibile ripristinare i file guest da una VM vVol a un host alternativo.
* Non è possibile ripristinare i file guest crittografati.

