---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__modify_built-in_schedules.html 
keywords:  
summary: Per modificare le pianificazioni integrate per i processi client VMware vSphere utilizzando il SnapCenter Plug-in for VMware vSphere , è necessario seguire la sequenza prescritta di chiamate API REST. 
---
= Flusso di lavoro API REST per modificare le pianificazioni integrate
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per modificare le pianificazioni integrate per i processi client VMware vSphere utilizzando il SnapCenter Plug-in for VMware vSphere , è necessario seguire la sequenza prescritta di chiamate API REST.

Le pianificazioni integrate sono quelle fornite come parte del prodotto; ad esempio, la pianificazione del dump del database MySQL.  È possibile modificare le seguenti pianificazioni:
`Schedule-DatabaseDump`
`Schedule-PurgeBackups`
`Schedule-AsupDataCollection`
`Schedule-ComputeStorageSaving`
`Schedule-PurgeJobs`

Per ogni API REST, aggiungi `\https://<server>:<port>` nella parte anteriore dell'API REST per formare un endpoint completo.

|===
| Fare un passo | API REST | Commenti 


| 1 | `/4.1/schedules` | `Get all built-in`schedules ottiene un elenco delle pianificazioni dei lavori originariamente fornite nel prodotto.  Annotare il nome della pianificazione che si desidera modificare e l'espressione cron associata. 


| 2 | `/4.1/schedules` | `Modify any built-in schedule`modifica la pianificazione indicata.  Passare il nome della pianificazione dal passaggio 1 e creare una nuova espressione cron per la pianificazione. 
|===