---
sidebar: sidebar 
permalink: scpivs44_extend_the_time_of_a_guest_file_restore_session.html 
keywords:  
summary: Per impostazione predefinita, un VMDK di ripristino file guest allegato è disponibile per 24 ore, dopodiché viene automaticamente scollegato.  È possibile estendere il tempo nella pagina Configurazione ospite. 
---
= Estendi il tempo di una sessione di ripristino dei file guest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per impostazione predefinita, un VMDK di ripristino file guest allegato è disponibile per 24 ore, dopodiché viene automaticamente scollegato.  È possibile estendere il tempo nella pagina *Configurazione ospite*.

.Informazioni su questo compito
Potrebbe essere necessario estendere una sessione di ripristino file guest se si desidera ripristinare in un secondo momento file o cartelle aggiuntivi dal VMDK allegato.  Tuttavia, poiché le sessioni di ripristino dei file guest utilizzano molte risorse, l'estensione della durata della sessione dovrebbe essere eseguita solo occasionalmente.

.Passi
. Nel client VMware vSphere, selezionare *Guest File Restore*.
. Selezionare una sessione di ripristino file guest, quindi selezionare l'icona Estendi sessione guest selezionata nella barra del titolo di Guest Session Monitor.
+
La sessione è prorogata di altre 24 ore.


