---
sidebar: sidebar 
permalink: scpivs44_monitor_jobs.html 
keywords:  
summary: 'Dopo aver eseguito un"operazione di protezione dei dati utilizzando il client VMware vSphere, è possibile monitorare lo stato del processo dalla scheda Job Monitor nella Dashboard e visualizzare i dettagli del processo.' 
---
= Monitorare i lavori
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver eseguito un'operazione di protezione dei dati utilizzando il client VMware vSphere, è possibile monitorare lo stato del processo dalla scheda Job Monitor nella Dashboard e visualizzare i dettagli del processo.

.Passi
. Dalla pagina di scelta rapida del client vCenter, selezionare SnapCenter Plug-in for VMware vSphere (SCV).
. Nel riquadro di navigazione sinistro di SCV, seleziona *Dashboard*.
. Quando due o più vCenter sono configurati in modalità collegata, selezionare l'istanza del plug-in SCV e selezionare la scheda *Job Monitor*.  La scheda Monitoraggio lavori elenca ogni lavoro, il suo stato, l'ora di inizio e l'ora di fine.  Se i nomi dei lavori sono lunghi, potrebbe essere necessario scorrere verso destra per visualizzare gli orari di inizio e fine.  Il display viene aggiornato ogni 30 secondi.
+
** Selezionare l'icona di aggiornamento nella barra degli strumenti per aggiornare la visualizzazione su richiesta.
** Seleziona l'icona del filtro per scegliere l'intervallo di tempo, il tipo, il tag e lo stato dei lavori che desideri visualizzare.  Il filtro distingue tra maiuscole e minuscole.
** Selezionare l'icona di aggiornamento nella finestra Dettagli lavoro per aggiornare la visualizzazione mentre il lavoro è in esecuzione.




Se la Dashboard non visualizza le informazioni sul lavoro, fare riferimento a https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_vSphere_web_client_dashboard_does_not_display_jobs["Articolo della Knowledge Base: la dashboard del client SnapCenter vSphere non visualizza i processi"^] .
