---
sidebar: sidebar 
permalink: scpivs44_configure_credentials_for_vm_guest_file_restores.html 
keywords:  
summary: Quando si collega un disco virtuale per operazioni di ripristino di file o cartelle guest, la macchina virtuale di destinazione per il collegamento deve disporre di credenziali configurate prima del ripristino. 
---
= Configurare le credenziali per i ripristini dei file guest della VM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si collega un disco virtuale per operazioni di ripristino di file o cartelle guest, la macchina virtuale di destinazione per il collegamento deve disporre di credenziali configurate prima del ripristino.

.Informazioni su questo compito
Nella tabella seguente sono elencati i requisiti delle credenziali per le operazioni di ripristino guest.

|===
|  | Controllo di accesso utente abilitato | Controllo di accesso utente disabilitato 


| Utente del dominio | Un utente di dominio con "amministratore" come nome utente funziona correttamente.  Ad esempio, "NetApp\administrator".  Tuttavia, un utente di dominio con "xyz" come nome utente che appartiene a un gruppo di amministratori locali non funzionerà.  Ad esempio, non è possibile utilizzare "NetApp\xyz". | Funziona bene sia un utente di dominio con "amministratore" come nome utente, sia un utente di dominio con "xyz" come nome utente appartenente a un gruppo di amministratori locali.  Ad esempio, "NetApp\administrator" o "NetApp\xyz". 


| Utente del gruppo di lavoro | Un utente locale con "amministratore" come nome utente funziona correttamente.  Tuttavia, un utente locale con "xyz" come nome utente appartenente a un gruppo di amministratori locali non funzionerà. | Funziona bene sia un utente locale con "amministratore" come nome utente, sia un utente locale con "xyz" come nome utente appartenente a un gruppo di amministratori locali.  Tuttavia, un utente locale con "xyz" come nome utente che non appartiene al gruppo di amministratori locali non funzionerà. 
|===
Negli esempi precedenti, "NetApp" è il nome di dominio fittizio e "xyz" è il nome utente locale fittizio

.Passi
. Dalla finestra dei collegamenti del client vSphere, selezionare * SnapCenter Plug-in for VMware vSphere* in Plug-in.
. Nella barra di navigazione a sinistra seleziona *Ripristino file ospite*.
. Nella sezione *Esegui come credenziali*, effettuare una delle seguenti operazioni:
+
|===
| Per fare questo… | Fai questo… 


| Utilizza le credenziali esistenti | Selezionare una qualsiasi delle credenziali configurate. 


| Aggiungi nuove credenziali  a| 
.. Selezionare *Aggiungi*.
.. Nella finestra di dialogo *Esegui come credenziali*, immettere le credenziali.  Per Nome utente, devi inserire “Amministratore”.
.. Selezionare *Seleziona VM*, quindi selezionare una VM nella finestra di dialogo *VM proxy*.  Selezionare *Salva* per tornare alla finestra di dialogo *Esegui come credenziali*.  Selezionare la macchina virtuale da utilizzare per autenticare le credenziali.


|===
+
Il SnapCenter Plug-in for VMware vSphere utilizza le credenziali selezionate per accedere alla VM selezionata.

. Seleziona *Salva*.

