---
sidebar: sidebar 
permalink: scpivs44_guest_file_restore_scenarios_you_might_encounter.html 
keywords:  
summary: 'Quando si tenta di ripristinare un file guest, potrebbero verificarsi situazioni in cui la sessione di ripristino del file guest è vuota, l"operazione di collegamento del disco di ripristino del file guest non riesce o i backup non vengono scollegati dopo l"interruzione della sessione di ripristino del file guest.' 
---
= Scenari di ripristino dei file guest che potresti incontrare
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si tenta di ripristinare un file guest, è possibile che si verifichi uno dei seguenti scenari.



== La sessione di ripristino dei file guest è vuota

Questo problema si verifica quando si crea una sessione di ripristino file guest e, mentre tale sessione è attiva, il sistema operativo guest viene riavviato.  Quando ciò si verifica, i VMDK nel sistema operativo guest potrebbero rimanere offline.  Pertanto, quando si tenta di esplorare la sessione di ripristino dei file guest, l'elenco è vuoto.

Per correggere il problema, rimettere manualmente online i VMDK nel sistema operativo guest.  Quando i VMDK sono online, la sessione di ripristino dei file guest visualizzerà il contenuto corretto.



== L'operazione di collegamento del disco al ripristino del file guest non riesce

Questo problema si verifica quando si avvia un'operazione di ripristino di file guest, ma l'operazione di collegamento del disco non riesce anche se VMware Tools è in esecuzione e le credenziali del sistema operativo guest sono corrette.  Se ciò si verifica, viene restituito il seguente errore:

`Error while validating guest credentials, failed to access guest system using specified credentials: Verify VMWare tools is running properly on system and account used is Administrator account, Error is SystemError vix error codes = (3016, 0).`

Per correggere il problema, riavviare il servizio VMware Tools Windows sul sistema operativo guest, quindi riprovare l'operazione di ripristino del file guest.



== L'email dell'ospite mostra ?????? per il nome del file

Questo problema si verifica quando si utilizza la funzionalità di ripristino file guest per ripristinare file o cartelle con caratteri non inglesi nei nomi e la notifica e-mail visualizza "??????" per i nomi dei file ripristinati.  L'allegato e-mail elenca correttamente i nomi dei file e delle cartelle ripristinati.



== I backup non vengono scollegati dopo l'interruzione della sessione di ripristino dei file guest

Questo problema si verifica quando si esegue un'operazione di ripristino di file guest da un backup coerente con la VM.  Mentre la sessione di ripristino dei file guest è attiva, viene eseguito un altro backup coerente con la VM per la stessa VM.  Quando la sessione di ripristino dei file guest viene disconnessa, manualmente o automaticamente dopo 24 ore, i backup per la sessione non vengono scollegati.

Per correggere il problema, scollegare manualmente i VMDK collegati alla sessione di ripristino dei file guest attiva.
