---
sidebar: sidebar 
permalink: scv48_add_certificates_to_certificate_store.html 
keywords:  
summary: 'Aggiungere i certificati radice e intermedio dell"autorità di certificazione a VMware vCenter per considerare attendibile il certificato e gli artefatti con esso firmati.' 
---
= Aggiungere certificati al VMware Certificate Store
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di installare Open Virtual Appliance (OVA), aggiungere il certificato a vCenter.  Il file .tar contiene i certificati OVA, Entrust Root e Intermediate; i certificati si trovano nella cartella dei certificati.  La distribuzione OVA è supportata in VMware vCenter 7u1 e versioni successive.

Nelle versioni VMware vCenter 7.0.3 e successive, l'OVA firmato dal certificato Entrust non è più attendibile.  Per risolvere il problema è necessario eseguire la seguente procedura.

.Passi
. Accedere al vCenter Server tramite vSphere Client.
. Vai su *Amministrazione > Certificati > Gestione certificati*.
. Accanto a *Trusted Root Store*, seleziona *Aggiungi*
. Sfoglia e seleziona la posizione dei certificati Entrust Root e Intermediate.  Il certificato viene aggiunto in un pannello sotto *Certificati radice attendibili*. Una volta installati i certificati, OVA può essere verificato e distribuito.



NOTE: Se il file OVA scaricato non è manomesso, nella colonna *Editore* viene visualizzato *Certificato attendibile*.
